name: Scheduled E2E Tests

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2 AM UTC

jobs:
  scheduled-playwright-tests:
    uses: ./.github/workflows/playwright.yml
    with:
      test-suite: regression
      test-env: DEV
      version: latest
    secrets: inherit
