name: Scheduled E2E Tests
on:
  schedule:
    - cron: "0 6 * * 1-5" # Weekdays (Monâ€“Fri) at 06:00
jobs:
  trigger-playwright-tests:
    uses: ./.github/workflows/playwright.yml
    with:
      test-suite: "PROD"

    secrets: inherit
